spring.application.name=spring-boot-intellij

# 프로젝트 전체에 대한 로깅 레벨
#logging.level.root = INFO

#해당 패키지에 대한 로깅 레벨
logging.level.net.likelion.bebc25.intellij = DEBUG

# 로깅 패턴 지정
logging.pattern.console = %d{yyyy년 MM월 dd일 HH시 mm분 ss초} - %msg%n
logging.charset.console = UTF-8